### PR TITLE
Team 27

### PR DESCRIPTION
**Pull request by Lepozepo**
Team 27 
- Marcelo Reyna
- Sanketh Shetty
- Jean-Michel Saunier
- Wes Toth

### CODE REVIEW

**Comment by githubwei** [comment]
@Lepozepo please read again the submission guideline in the main repo Readme, you are supposed to create a subfolder with your team ID and have a detailed Readme of your project there. Please look at some of already submitted and merged projects as reference

**Comment by Lepozepo** [comment]
@githubwei hold on merging, we'll add a video tonight ^_^

**Comment by githubwei** [comment]
@Lepozepo yeah feel free to let me know when you are ready to merge

**Comment by Lepozepo** [comment]
@githubwei ok! Looks like we're good to go ^_^ thanks for organizing all of this, being new to public blockchain development this all makes it much easier for sure

**Comment by Lepozepo** [comment]
Ah, looks like everyone is adding the full source, I'll add that too real quick

**Comment by Lepozepo** [comment]
@githubwei ok, now it's ready ^_^

**Pull request merged**
